services:
  navidrome:
    image: deluan/navidrome:latest
    user: "1000:1000"
    ports:
      - "4533:4533"
    environment:
      - ND_LASTFM_ENABLED=true
      - ND_LASTFM_APIKEY=${LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${LASTFM_SECRET}
      - TZ=${TZ}
    volumes:
      - ./data:/data
      - /mnt/data/music:/music:ro
